version: '3'

services:
  php:
    container_name: php
    build: ./docker/php
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"


  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 8080:80
    - 443:443
    volumes:
    - ./:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php


  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: output
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
