version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.4.7-fpm
      - image: circleci/mysql:5.7
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - APP_KEY: base64:TC8LcgAd0jESLPN/HYT1s0/FCLxVrJuoMlfNSb2b2oI=
          - DB_CONNECTION: circle_test
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install pdo_mysql
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - restore_cache:
              keys:
                  - node-v1-{{ checksum "package-lock.json" }}
                  - node-v1-
      - save_cache:
              key: node-v1-{{ checksum "package-lock.json" }}
              paths:
                  - node_modules
      - run: php artisan key:generate
      - run: php artisan migrate  --env=testing --database=circle_test --force
      - run: ./vendor/bin/phpunit

  deploy:
    docker:
      - image: circleci/php:7.4.7-fpm
    enabled: true

    steps:
      - add_ssh_keys:
          fingerprints:
            - "a0:6b:cd:41:ce:8e:b1:d5:85:00:48:51:29:89:c3:4f"

      - run:
          name: SSH 経由のデプロイ
          command: |
            ssh $SSH_USER@$SSH_HOST "<remote deploy command>"

      - run:
          name: install aws cli
          command: |
              curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
              unzip awscli-bundle.zip
              sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws



workflows:
  version: 2
  build_and_deploy:
      jobs:
          - build
          - deploy:
              requires:
                  - build
              filters:
                  branches:
                      only: master
